### ISSUE TITLE
Is there a plan to support swagger 2.0

### ISSUE THREAD

**Issue by rahulmishra** [swagger-api/swagger-form-editor#2]
I love the utility of this tool for 1.2 but was wondering if you intended to support 2.0 at some point.

**Comment by MikeRalphson** [comment]
@rahulmishra Sorry to dig up an old issue, but a supported alternative is [OpenApi-GUI](https://github.com/mermade/openapi-gui) which you can see in action [here](https://mermade.github.io/openapi-gui)
